services:
  grq:
    build: .
    image: grq
    container_name: grq
    env_file:
      - .env-example
    ports:
      - "8080:80"
    volumes:
      - .:/backend
    networks:
      - grq-net
    depends_on:
      theBank:
        condition: service_healthy

  theBank:
    image: bitnami/postgresql:13
    container_name: theBank
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=userPass123
      - POSTGRESQL_DATABASE=getRichQuick_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data-new:/bitnami/postgresql
    networks:
      - grq-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hero -d heroes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:4.23
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin-new:/var/lib/pgadmin
    depends_on:
      - theBank
    networks:
      - grq-net

volumes:
  pg-data-new:
    name: pg-data-new
  pgadmin-new:
    name: pgadmin-new

networks:
  grq-net:
    name: grq-net
