"""update table

Revision ID: 0eab5516381d
Revises: b7ecda250e3b
Create Date: 2023-09-01 04:15:05.487891+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "0eab5516381d"
down_revision = "b7ecda250e3b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticker",
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk__ticker")),
    )
    op.create_index(op.f("ix__ticker__uuid"), "ticker", ["uuid"], unique=True)
    op.create_table(
        "option_chain",
        sa.Column("expiration_date", sa.DateTime(), nullable=False),
        sa.Column("ticker_uuid", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticker_uuid"],
            ["ticker.uuid"],
            name=op.f("fk__option_chain__ticker_uuid__ticker"),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk__option_chain")),
    )
    op.create_index(
        op.f("ix__option_chain__expiration_date"),
        "option_chain",
        ["expiration_date"],
        unique=True,
    )
    op.create_index(
        op.f("ix__option_chain__uuid"), "option_chain", ["uuid"], unique=True
    )
    op.create_table(
        "call_option_quote",
        sa.Column("contractSymbol", sa.String(length=50), nullable=False),
        sa.Column("lastTradeDate", sa.DateTime(), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("lastPrice", sa.Float(), nullable=False),
        sa.Column("bid", sa.Float(), nullable=False),
        sa.Column("ask", sa.Float(), nullable=False),
        sa.Column("change", sa.Float(), nullable=False),
        sa.Column("percentChange", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("openInterest", sa.Float(), nullable=True),
        sa.Column("impliedVolatility", sa.Float(), nullable=False),
        sa.Column("inTheMoney", sa.Boolean(), nullable=False),
        sa.Column("middle", sa.Float(), nullable=False),
        sa.Column("BidAskSpread", sa.Float(), nullable=False),
        sa.Column("option_chain_uuid", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["option_chain_uuid"],
            ["option_chain.uuid"],
            name=op.f(
                "fk__call_option_quote__option_chain_uuid__option_chain"
            ),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk__call_option_quote")),
    )
    op.create_index(
        op.f("ix__call_option_quote__BidAskSpread"),
        "call_option_quote",
        ["BidAskSpread"],
        unique=False,
    )
    op.create_index(
        op.f("ix__call_option_quote__ask"),
        "call_option_quote",
        ["ask"],
        unique=False,
    )
    op.create_index(
        op.f("ix__call_option_quote__bid"),
        "call_option_quote",
        ["bid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__call_option_quote__change"),
        "call_option_quote",
        ["change"],
        unique=False,
    )
    op.create_index(
        op.f("ix__call_option_quote__impliedVolatility"),
        "call_option_quote",
        ["impliedVolatility"],
        unique=False,
    )
    op.create_index(
        op.f("ix__call_option_quote__lastPrice"),
        "call_option_quote",
        ["lastPrice"],
        unique=False,
    )
    op.create_index(
        op.f("ix__call_option_quote__lastTradeDate"),
        "call_option_quote",
        ["lastTradeDate"],
        unique=True,
    )
    op.create_index(
        op.f("ix__call_option_quote__middle"),
        "call_option_quote",
        ["middle"],
        unique=False,
    )
    op.create_index(
        op.f("ix__call_option_quote__percentChange"),
        "call_option_quote",
        ["percentChange"],
        unique=False,
    )
    op.create_index(
        op.f("ix__call_option_quote__strike"),
        "call_option_quote",
        ["strike"],
        unique=False,
    )
    op.create_index(
        op.f("ix__call_option_quote__uuid"),
        "call_option_quote",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "put_option_quote",
        sa.Column("contractSymbol", sa.String(length=50), nullable=False),
        sa.Column("lastTradeDate", sa.DateTime(), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("lastPrice", sa.Float(), nullable=False),
        sa.Column("bid", sa.Float(), nullable=False),
        sa.Column("ask", sa.Float(), nullable=False),
        sa.Column("change", sa.Float(), nullable=False),
        sa.Column("percentChange", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("openInterest", sa.Float(), nullable=True),
        sa.Column("impliedVolatility", sa.Float(), nullable=False),
        sa.Column("inTheMoney", sa.Boolean(), nullable=False),
        sa.Column("middle", sa.Float(), nullable=False),
        sa.Column("BidAskSpread", sa.Float(), nullable=False),
        sa.Column("option_chain_uuid", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["option_chain_uuid"],
            ["option_chain.uuid"],
            name=op.f("fk__put_option_quote__option_chain_uuid__option_chain"),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk__put_option_quote")),
    )
    op.create_index(
        op.f("ix__put_option_quote__BidAskSpread"),
        "put_option_quote",
        ["BidAskSpread"],
        unique=False,
    )
    op.create_index(
        op.f("ix__put_option_quote__ask"),
        "put_option_quote",
        ["ask"],
        unique=False,
    )
    op.create_index(
        op.f("ix__put_option_quote__bid"),
        "put_option_quote",
        ["bid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__put_option_quote__change"),
        "put_option_quote",
        ["change"],
        unique=False,
    )
    op.create_index(
        op.f("ix__put_option_quote__impliedVolatility"),
        "put_option_quote",
        ["impliedVolatility"],
        unique=False,
    )
    op.create_index(
        op.f("ix__put_option_quote__lastPrice"),
        "put_option_quote",
        ["lastPrice"],
        unique=False,
    )
    op.create_index(
        op.f("ix__put_option_quote__lastTradeDate"),
        "put_option_quote",
        ["lastTradeDate"],
        unique=True,
    )
    op.create_index(
        op.f("ix__put_option_quote__middle"),
        "put_option_quote",
        ["middle"],
        unique=False,
    )
    op.create_index(
        op.f("ix__put_option_quote__percentChange"),
        "put_option_quote",
        ["percentChange"],
        unique=False,
    )
    op.create_index(
        op.f("ix__put_option_quote__strike"),
        "put_option_quote",
        ["strike"],
        unique=False,
    )
    op.create_index(
        op.f("ix__put_option_quote__uuid"),
        "put_option_quote",
        ["uuid"],
        unique=True,
    )
    op.drop_index("ix__hrs_heroes__nickname", table_name="hrs_heroes")
    op.drop_index("ix__hrs_heroes__uuid", table_name="hrs_heroes")
    op.drop_table("hrs_heroes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hrs_heroes",
        sa.Column(
            "nickname",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "role",
            postgresql.ENUM(
                "mage",
                "assassin",
                "warrior",
                "priest",
                "tank",
                name="hrs_roles",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid", name="pk__hrs_heroes"),
    )
    op.create_index(
        "ix__hrs_heroes__uuid", "hrs_heroes", ["uuid"], unique=False
    )
    op.create_index(
        "ix__hrs_heroes__nickname", "hrs_heroes", ["nickname"], unique=False
    )
    op.drop_index(
        op.f("ix__put_option_quote__uuid"), table_name="put_option_quote"
    )
    op.drop_index(
        op.f("ix__put_option_quote__strike"), table_name="put_option_quote"
    )
    op.drop_index(
        op.f("ix__put_option_quote__percentChange"),
        table_name="put_option_quote",
    )
    op.drop_index(
        op.f("ix__put_option_quote__middle"), table_name="put_option_quote"
    )
    op.drop_index(
        op.f("ix__put_option_quote__lastTradeDate"),
        table_name="put_option_quote",
    )
    op.drop_index(
        op.f("ix__put_option_quote__lastPrice"), table_name="put_option_quote"
    )
    op.drop_index(
        op.f("ix__put_option_quote__impliedVolatility"),
        table_name="put_option_quote",
    )
    op.drop_index(
        op.f("ix__put_option_quote__change"), table_name="put_option_quote"
    )
    op.drop_index(
        op.f("ix__put_option_quote__bid"), table_name="put_option_quote"
    )
    op.drop_index(
        op.f("ix__put_option_quote__ask"), table_name="put_option_quote"
    )
    op.drop_index(
        op.f("ix__put_option_quote__BidAskSpread"),
        table_name="put_option_quote",
    )
    op.drop_table("put_option_quote")
    op.drop_index(
        op.f("ix__call_option_quote__uuid"), table_name="call_option_quote"
    )
    op.drop_index(
        op.f("ix__call_option_quote__strike"), table_name="call_option_quote"
    )
    op.drop_index(
        op.f("ix__call_option_quote__percentChange"),
        table_name="call_option_quote",
    )
    op.drop_index(
        op.f("ix__call_option_quote__middle"), table_name="call_option_quote"
    )
    op.drop_index(
        op.f("ix__call_option_quote__lastTradeDate"),
        table_name="call_option_quote",
    )
    op.drop_index(
        op.f("ix__call_option_quote__lastPrice"),
        table_name="call_option_quote",
    )
    op.drop_index(
        op.f("ix__call_option_quote__impliedVolatility"),
        table_name="call_option_quote",
    )
    op.drop_index(
        op.f("ix__call_option_quote__change"), table_name="call_option_quote"
    )
    op.drop_index(
        op.f("ix__call_option_quote__bid"), table_name="call_option_quote"
    )
    op.drop_index(
        op.f("ix__call_option_quote__ask"), table_name="call_option_quote"
    )
    op.drop_index(
        op.f("ix__call_option_quote__BidAskSpread"),
        table_name="call_option_quote",
    )
    op.drop_table("call_option_quote")
    op.drop_index(op.f("ix__option_chain__uuid"), table_name="option_chain")
    op.drop_index(
        op.f("ix__option_chain__expiration_date"), table_name="option_chain"
    )
    op.drop_table("option_chain")
    op.drop_index(op.f("ix__ticker__uuid"), table_name="ticker")
    op.drop_table("ticker")
    # ### end Alembic commands ###
